### ISSUE TITLE
need a way to pass $allowTimeout into waitResponse througth sendRequest function

### ISSUE THREAD

**Issue by russelomua** [ofbeaton/phpami#6]
https://github.com/ofbeaton/phpami/blob/0d46709be6237ff2035c407f5d6cad33325c695d/src/Ami.php#L165

in sendRequest function used waitResponse function.
sometimes waitResponse function is looping and its happening when $type equal '';
so i thing need a way to pass $allowTimeout variable trougth sendRequest function with default value false;

**Comment by ofbeaton** [comment]
OK things are a bit hectic right now, can you please put a PR together?

**Comment by russelomua** [comment]
Create pull request #7 

Also found your comment for waitResponse function:
> If a request was just sent, this will return the response.
> Otherwise, it will loop forever, handling events.

looping cause sometimes after run `$ami->command('Queue show');`
so if i add `$ami->allowTimeout();` prevoiusly then looping goes out

**Comment by ofbeaton** [comment]
Thanks for the PR! merged and tagged.

**Comment by russelomua** [comment]
:+1:  Can you run update on composer [https://packagist.org/packages/ofbeaton/phpami](url) please?

**Comment by ofbeaton** [comment]
Fixed, sorry the deps got renamed. Should be good now.

**Comment by russelomua** [comment]
i mean on packagist still 1.0.3 is latest version

![what i mean](https://user-images.githubusercontent.com/313658/64185291-8dfa5700-ce75-11e9-9c4c-847601a35e47.png)


i think need to press **Update** button to fetch last updates to packagist
![how to fix](https://user-images.githubusercontent.com/313658/64185318-98b4ec00-ce75-11e9-9ff7-b12bf140c8d1.png)

i'm sorry for importunity 😨

**Comment by ofbeaton** [comment]
done
